DancerPortfolio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic import RedirectView

from DancerPortfolio import settings
from ballerine_app.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("ballerine_app.urls", namespace="portfolio")),
    url(
        r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('img/favicon.png'),
            permanent=False),
        name="favicon"
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ballerine_app/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static

from DancerPortfolio import settings
from .views import (
    home,
    contact,
    gallery,
    about,
    comment)

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^contact/$', contact, name="contact"),
    url(r'^about/$', about, name="about"),
    url(r'^gallery/$', gallery, name="gallery"),
    url(r'^comment/$', comment, name="comment"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}'">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    {% block links %}

    {% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Open+Sans:300,400,700&amp;subset=cyrillic"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway:300,400" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;subset=cyrillic-ext"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'home.css' %}">
    {% block page_css %}

    {% endblock %}


</head>
<body>
<div class="wrapper">

    {% block header %}
        <div class="clearfix">
            <div class="head">
                <div class="container">
                    {#                <ul class="nav navbar-nav pull-right">#}
                    {#                    <li class="nav-item active">#}
                    {#                        <a class="nav-linke" href="#">Home <span class="sr-only">(current)</span></a>#}
                    {#                    </li>#}
                    {#                    <li class="nav-item">#}
                    {#                        <a class="nav-link" href="#">About me</a>#}
                    {#                    </li>#}
                    {#                    <li class="nav-item">#}
                    {#                        <a class="nav-link" href="#">Contact</a>#}
                    {#                    </li>#}
                    {#                </ul>#}
                    <div class="pull-right">
                        <p class="navbar-text"><a href="{% url 'portfolio:home' %}">Home</a></p>
                        <p class="navbar-text"><a href="{% url 'portfolio:about' %}">About</a></p>
                        <p class="navbar-text"><a href="{% url 'portfolio:gallery' %}">Gallery</a></p>
                        <p class="navbar-text"><a href="{% url 'portfolio:contact' %}">Contact</a></p>
                        <p class="navbar-text"><a href="{% url 'portfolio:comment' %}">Comment</a></p>
                    </div>
                </div>
            </div>
        </div>


    {% endblock %}

    {% block content %}{% endblock %}


    {% block footer %}
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="btn"><a href="{% url 'portfolio:home' %}">Home</a></div>
                        <div class="btn"><a href="{% url 'portfolio:about' %}">About</a></div>
                        <div class="btn"><a href="{% url 'portfolio:gallery' %}">Gallery</a></div>
                        <div class="btn"><a href="{% url 'portfolio:contact' %}">Contact</a></div>
                        <div class="btn"><a href="{% url 'portfolio:comment' %}">Comment</a></div>
                    </div>
                </div>
                <div class="row">
                    <hr>
                    <div class="col-sm-12">
                        <p class="footer_p_to_insert">
                            <small>
                                {% block footer_copyright %}
                                {% endblock %}
                            </small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
</div>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="{% static 'js/common.js' %}"></script>
<script src="{% static 'js/experemental.js' %}"></script>
{% block script_base %}

{% endblock %}
</body>
</html>

templates/comment.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_title %}
    {{ head_title }}
{% endblock %}


{% block page_css %}
    <link rel="stylesheet" href="{% static 'contact.css' %}">
    <link rel="stylesheet" href="{% static 'comment.css' %}">
{% endblock %}

{% block content %}
    <div class="container main_thumbnail">
        <div class="col-sm-6 col-sm-offset-3">
            {% if comments %}
                {% for comment in comments %}
                    <div class="row">
                        <p class="name">{{ comment.name }}</p>
                        <p class="message">{{ comment.message }}</p>
                        <small class="emailTime">{{ comment.email }} {{ comment.timestamp }}</small>
                    </div>
                {% endfor %}

            {% endif %}
            <form action="" method="post">{% csrf_token %}
                {{ form.non_field_errors }}
                <div class="row">{{ form.name.errors }}
                    {{ form.name }}
                    {{ form.email.errors }}
                    {{ form.email }}</div>
                <div class="row">
                    {{ form.message.errors }}
                    {{ form.message }}</div>
                <div class="row">
                    <input type="submit" class="btn" value="{{ form_button_palceholder.content }}">
                </div>

            </form>
            {% if comments %}
                {% for comment in messages %}
                    <h4{% if message.tags %} class="{{ message.tags }} text-center message"{% endif %}>
                        <span>{{ message }}</span></h4>
                {% endfor %}
            {% endif %}

        </div>
    </div>
{% endblock %}

{% block script_base %}
    <script src="{% static 'js/comment.js' %}"></script>
{% endblock %}

{% block footer_copyright %}
    {{ footer_copyright.content }}
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_title %}
    {{ contact_title.content }}
{% endblock %}

{% block page_css %}
    <link rel="stylesheet" href="{% static 'contact.css' %}">
{% endblock %}

{% block content %}
    <div class="container main_thumbnail">
            <div class="col-sm-8 col-sm-offset-2 text-center">
            <div class="row">
                <h1>{{ first_textblock.content }}</h1>
                <hr>
                <h4>{{ second_textblock.content }}</h4>
                <br>
                <h4>{{ third_textblock.content }}</h4>
                <br>
                <h4>{{ fourth_textblock.content }}</h4>
                <hr>
                <div class="socials_block">
                    {% for item in socials %}
                        <div class="btn social">
                            <a href="{% if item.url %}{{ item.url }}{% endif %}">
                                {{ item.title }}
                            </a>
                        </div>
                {% endfor %}
                </div></div>
                <hr>
            </div>
        <div class="col-sm-6 col-sm-offset-3">
        <div class="row">
            <h5 class="text-center">If you have offers or suggestions, don't be afraid to drop me a message</h5>
{#            <form action="">#}
{#                <input type="text" placeholder="{{ form_name_palceholder.content }}" class="col-sm-5">#}
{#                <input type="email" placeholder="{{ form_email_palceholder.content }}" class="col-sm-6 col-sm-offset-1">#}
{#                <textarea placeholder="{{ form_message_palceholder.content }}" class="col-sm-12 message_field"></textarea>#}
{#                <input type="submit" class="btn" value="{{ form_button_palceholder.content }}">#}
{#            </form>#}
        </div>
            <form action="" method="post">{% csrf_token %}
            {{ form.non_field_errors }}
                <div class="row">{{ form.name.errors }}
                {{ form.name }}
                {{ form.email.errors }}
                {{ form.email }}</div>
                <div class="row">
                {{ form.message.errors }}
                {{ form.message }}</div>
                <div class="row">
                    <input type="submit" class="btn" value="{{ form_button_palceholder.content }}">
                </div>

            </form>
            {% if messages %}
                    {% for message in messages %}
                        <h4{% if message.tags %} class="{{ message.tags }} text-center message"{% endif %}><span>{{ message }}</span></h4>
                    {% endfor %}
            {% endif %}

        </div>
    </div>
{% endblock %}

{% block script_base %}
    <script src="{% static 'js/contact.js' %}"></script>
{% endblock %}

{% block footer_copyright %}
    {{ footer_copyright.content }}
{% endblock %}

templates/gallery.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_title %}
    {{ gallery_title.content }}
{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static 'libs/Fotorama/fotorama.css' %}">
    <script src="{% static 'libs/Fotorama/fotorama.js' %}"></script>
{% endblock %}

{% block page_css %}
    <link rel="stylesheet" href="{% static 'gallery.css' %}">
{% endblock %}

{% block content %}

<div class="fotorama style='background: url('{{ fotorama_background.img.url }}')'"
     data-allowfullscreen="true"
     data-fit="contain"
     data-loop="true"
     data-width="100%"
     data-maxheight="600px"
     data-nav="thumbs"
     data-arrows="false"
     data-click="true"
     data-thumbborderwidth="0"
     data-trackpad="true"
     data-swipe="true">
    {% for item in images %}
        <img src="{{ item.img.url }}" alt="">
    {% endfor %}

</div>

{% endblock %}

{% block footer_copyright %}
{{ footer_copy.content }}
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}


{% block head_title %}
    {{ home_title.content }}
{% endblock %}

{% block links %}
{% endblock %}

{% block content %}
    <div class="first_section" style="background: url({{ first_section_bg.img.url }}); background-size: cover;background-position: center top;">
        <div class="container">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="jumbotron first_section_jumbotron">
                    <h1>{{ first_section_h1.content }}</h1>
                    <p class="lead">{{ first_section_p.content }}</p>
                </div>
                <div class="row"><img src="{% static 'img/mouse-with-wheel.gif' %}" alt="" class="mouse-wheel"></div>
            </div>
        </div>
    </div>

    <div class="second_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-xs-12">
                    <h2>{{ second_section_h2.content }}</h2>
                    <hr>
                    <p>{{ second_section_p.content }}</p>
                </div>
                <div class="col-sm-6 col-xs-12 second_section_img">
                    <img src="{{ second_section_image.img.url }}" alt="" class="img-responsive img-thumbnail">
                </div>
            </div>
        </div>
    </div>

    <div class="third_section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-xs-12 second_section_img">
                    <img src="{{ third_section_image.img.url }}" alt="" class="img-responsive img-thumbnail">
                </div>
                <div class="col-sm-6 col-xs-12">
                    <h2>{{ third_section_h2.content }}</h2>
                    <hr>
                    <p>{{ third_section_p.content }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="fourth_section">
        <div class="container text-center">
            <h1 class="text-center">Gallery</h1>
            <hr>
            <div class="col-sm-10 col-sm-offset-1">
                <div class="row">

                    {% for item in mini_gallery %}
                        <div class="col-sm-4 col-xs-6">
                            <a class="popup_image" href="{% url 'portfolio:gallery' %}">
                               <img src="{% if item.image %}{{ item.image.url }}{% endif %}" alt="" class="img-responsive img-thumbnail">
                            </a>
                        </div>
                        {% cycle '' '' '</div><div class="row">' %}
                    {% endfor %}

                </div>
                <div class="btn"><a href="{% url 'portfolio:gallery' %}">View gallery</a></div>
            </div>
        </div>
    </div>

    <div class="fifth_section" style="background: url({% static 'img/fifth_section.gif' %});background-size: cover;background-position: center;">
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <h1>Contact me:</h1>
                </div>
                <div class="col-sm-4">
                    {% for item in socials %}
                        <div class="btn btn-inverse">
                            <a href="{% if item.url %}{{ item.url }}{% endif %}">
                                {{ item.title }}
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block page_css %}
    <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

{% block footer_copyright %}
{{ footer_copy.content }}
{% endblock %}